# .streamlit/secrets.toml
[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1K2d32XmZQMdGLslNzv2ZZoUquARl6yiKRT5SjUkTtIY/edit#gid=0"
OPENAI_API_KEY = "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"